# Generated by Django 6.0.7 on 2026-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default=None, max_length=20),
        ),
    ]
