# Generated by Django 6.0.7 on 2026-07-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_auth_provider_oauthcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthcredential',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
