# Generated by Django 6.0.7 on 2026-07-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_oauthcredential_refresh_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthcredential',
            options={'ordering': ['-created_at']},
        ),
    ]
